version: "3.1"
services:
  backend:
    image: behzadkha/tfximg
    volumes:
      - "./gnufx-server/images:/gnufx-server/images"
    ports:
      - "3001:3001"
  client:
    image: behzadkha/tfximgfront
    links:
      - "backend"
    ports:
      - "3000:3000"
    stdin_open: true
