name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.4, 10.x, 8.x]
    steps:
    - uses: actions/checkout@v1
    - name: npm install client
      run: |
        cd gnufx-client
        npm install
    - name: npm install server
      run: |
        cd gnufx-server
        npm install
    - name: testing client
      run: |
        cd gnufx-client
        npm run unitTest
    - name: testing server
      run: |
        cd gnufx-server
        npm run test
        echo "Exited with '$?'"
    - name: npm run build for deployment (later)
      run: |
        cd gnufx-client
        npm run build
      